### ISSUE TITLE
CSS Stylesheet public 

### ISSUE THREAD

**Issue by CodeRed30** [CodeRed30/monarchmakersbnb#16]
Instructions from Ollie on fixing: 

Miranda says if we put this:
configure do
    set :public_dir, "public"
  end
inside our app class, our css from stylesheet will span across all pages.

Is basically explicitly setting our public folder as 'public'

**Comment by hacaravan** [comment]
Use a layout.erb file and you shouldn't need too much on each individual erb file

**Comment by CodeRed30** [comment]
Great work @bateso88
